---
version: '3.9'

services:
  web:
    image: nginx:latest
    network_mode: "host"
    volumes:
      - ./src:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
  php-fpm:
    image: php:8-fpm
    network_mode: "host"
    volumes:
      - ./src:/var/www/html